### ISSUE TITLE
App fails when run inside Docker container due to psycopg2.ProgrammingError: relation APIimports_feature does not exist

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/transportation-backend#30]
Travis build now succeeds, tests pass, deployment is working to ECS.  However, container will not successfully service client request traffic as the application inside the container fails to run correctly due to some broken dependencies or similar issue.

This can be reproduced by checking out the latest commit from the `migratedb` branch and running `source bin/env.sh` then `bin/start-proj.sh -l` and browsing to http://127.0.0.1:8000/transport/features/:

```
...
.
.
.
Step 9/9 : WORKDIR /code/
 ---> Using cache
 ---> 4813caaf340b
Successfully built 4813caaf340b
bin/start-proj.sh -l
WARNING: The DEPLOY_TARGET variable is not set. Defaulting to a blank string.
WARNING: The CONFIG_BUCKET variable is not set. Defaulting to a blank string.
Removing transportationbackend_transport-service_1
Recreating c569849b717b_transportationbackend_transport-service_1
Attaching to transportationbackend_transport-service_1
transport-service_1  | Performing system checks...
transport-service_1  | 
transport-service_1  | System check identified no issues (0 silenced).
transport-service_1  | 
transport-service_1  | You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): APIimports, admin, auth, contenttypes, sessions.
transport-service_1  | Run 'python manage.py migrate' to apply them.
transport-service_1  | April 09, 2017 - 05:39:36
transport-service_1  | Django version 1.10.5, using settings 'transDjango.settings'
transport-service_1  | Starting development server at http://0.0.0.0:8000/
transport-service_1  | Quit the server with CONTROL-C.
transport-service_1  | Not Found: /transport/
transport-service_1  | [09/Apr/2017 05:41:15] "GET /transport/ HTTP/1.1" 404 2425
transport-service_1  | Not Found: /transport/admin/
transport-service_1  | [09/Apr/2017 05:41:22] "GET /transport/admin/ HTTP/1.1" 404 2443
transport-service_1  | Internal Server Error: /transport/features/
transport-service_1  | Traceback (most recent call last):
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
transport-service_1  |     return self.cursor.execute(sql, params)
transport-service_1  | psycopg2.ProgrammingError: relation "APIimports_feature" does not exist
transport-service_1  | LINE 1: ..."."source_name", "APIimports_feature"."data" FROM "APIimport...
transport-service_1  |                                                              ^
transport-service_1  | 
transport-service_1  | 
transport-service_1  | The above exception was the direct cause of the following exception:
transport-service_1  | 
transport-service_1  | Traceback (most recent call last):
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
transport-service_1  |     response = get_response(request)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
transport-service_1  |     response = self.process_exception_by_middleware(e, request)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
transport-service_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
transport-service_1  |     return view_func(*args, **kwargs)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
transport-service_1  |     return self.dispatch(request, *args, **kwargs)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
transport-service_1  |     response = self.handle_exception(exc)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
transport-service_1  |     self.raise_uncaught_exception(exc)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
transport-service_1  |     response = handler(request, *args, **kwargs)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/generics.py", line 240, in get
transport-service_1  |     return self.list(request, *args, **kwargs)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/mixins.py", line 48, in list
transport-service_1  |     return Response(serializer.data)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework_gis/serializers.py", line 20, in data
transport-service_1  |     return super(ListSerializer, self).data
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 262, in data
transport-service_1  |     self._data = self.to_representation(self.instance)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework_gis/serializers.py", line 28, in to_representation
transport-service_1  |     ("features", super(GeoFeatureModelListSerializer, self).to_representation(data))
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/rest_framework/serializers.py", line 647, in to_representation
transport-service_1  |     self.child.to_representation(item) for item in iterable
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __iter__
transport-service_1  |     self._fetch_all()
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1087, in _fetch_all
transport-service_1  |     self._result_cache = list(self.iterator())
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
transport-service_1  |     results = compiler.execute_sql()
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
transport-service_1  |     cursor.execute(sql, params)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
transport-service_1  |     return super(CursorDebugWrapper, self).execute(sql, params)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
transport-service_1  |     return self.cursor.execute(sql, params)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
transport-service_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
transport-service_1  |     raise value.with_traceback(tb)
transport-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
transport-service_1  |     return self.cursor.execute(sql, params)
transport-service_1  | django.db.utils.ProgrammingError: relation "APIimports_feature" does not exist
transport-service_1  | LINE 1: ..."."source_name", "APIimports_feature"."data" FROM "APIimport...
```

**Comment by imbellish** [comment]
Really
